[check]
target-std = "f2008"
select = ['ALL']
ignore = [
    "literal-kind",
    "literal-kind-suffix",
    "function-missing-result",
    "exit-or-cycle-in-unlabelled-loop",
    "incorrect-space-before-comment",
    "missing-default-case",
    "mixed-scalar-array-declaration",
    "invalid-character", # BOM is treated invalid
    "multiple-statements-per-line",
]
line-length = 101  # throws error if length > 100
preview = true