# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
        numpy-version: [ "1.26.4", "latest" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          sudo apt install -yqqq gnuplot=5.4.2+dfsg2-2
          python -m pip install --upgrade pip
          python -m pip install ruff fortitude-lint
          if [ "${{ matrix.numpy-version }}" = "latest" ]; then
            pip install .
          else
            echo "Installing numpy==${{ matrix.numpy-version }}"
            pip install numpy==${{ matrix.numpy-version }} .
          fi
      - name: Lint with ruff
        run: |
          ruff check
      - name: Lint with fortitude
        run: |
          fortitude check
      - name: Run unittests
        run: |
          python -m unittest discover tests/
      - name: Run 'Response' regression test
        run: |
          cd examples/response
          PYTHONUNBUFFERED=1 ./run.py ../grids/naca0004_129x385.plot3d 1.008930 0.5 0 | tee run.out
          diff run.out Ma0p5.out
          cd -
      - name: Check 'Response' plots
        run: |
          cd examples/response
          ./bode.gpi
          git diff --exit-code bode.png
          ./sinusoidal.gpi
          git diff --exit-code sinusoidal.gif
          cd -