# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-22.04
    container:
      image: python:3.12-bookworm
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        runner: [ "A", "B", "C", "D", "E", "F", "G" ]

    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            openmpi-bin \
            gfortran \
            libmumps-dev \
            gnuplot
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Check 'Response' example
        working-directory: examples/response
        run: |
          mpirun --allow-run-as-root -n 1 --report-bindings \
            python -u run.py ../grids/naca0004_129x129.plot3d 10. 0.5 0 | tee run.out
          diff run.out Ma0p50.out