# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
        numpy-version: [ "1.26.4" ]
        runner: [ "A", "B", "C", "D", "E", "F", "G" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          sudo apt install -yqqq libmumps-dev gnuplot=5.4.2+dfsg2-2
          python -m pip install --upgrade pip
          python -m pip install ruff==0.15.0 fortitude-lint==0.8.0
          if [ "${{ matrix.numpy-version }}" = "latest" ]; then
            pip install .
          else
            echo "Installing numpy==${{ matrix.numpy-version }}"
            pip install numpy==${{ matrix.numpy-version }} .
          fi
      - name: Check 'Response' example
        working-directory: examples/response
        run: |
          mpirun -n 1 --report-bindings --bind-to hwthread \
            python -u run.py ../grids/naca0004_129x129.plot3d 10. 0.5 0 | tee Ma0p50.out
          git diff --exit-code Ma0p50.out